/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../assets/styles/globals.scss";
import NavbarComponent from "@/components/navbarcomponent";
import Providers from "./providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <header>
            <NavbarComponent />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
